using UnityEngine;
using UnityEngine.SceneManagement;


public class PlayerHealth : MonoBehaviour
{

    [Header("Health Settings")]
    public int maxLives = 3;
    public int CurrentLives { get; private set; }

    void Start()
    {
        CurrentLives = maxLives;
    }

    // Ø¨Ø±Ø®ÙˆØ±Ø¯ ÙÛŒØ²ÛŒÚ©ÛŒ (Ø¨Ø¯Ù† Ø¯Ø´Ù…Ù†)
    void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.collider.CompareTag("Enemy"))
        {
            TakeDamage();
        }
    }

    // Ø¨Ø±Ø®ÙˆØ±Ø¯ Trigger (Ú†Ø§Ù‚Ùˆ / ØªÙˆÙ¾)
    void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Projectile"))
        {
            TakeDamage();
            Destroy(other.gameObject); // Ù¾Ø±ØªØ§Ø¨Ù‡ Ù†Ø§Ø¨ÙˆØ¯ Ø´Ù‡
        }
    }

    void TakeDamage()
    {
        CurrentLives--;
        Debug.Log("Ø¬ÙˆÙ† Ø¨Ø§Ù‚ÛŒâ€ŒÙ…Ø§Ù†Ø¯Ù‡: " + CurrentLives);

        if (CurrentLives <= 0)
        {
            GameOver();
        }
    }

    void GameOver()
    {
        Debug.Log("ğŸ’€ Game Over!");
        FindObjectOfType<GameManageer>().GameOver();
    }
}

